export enum EnumPostType {
    TEKNOLOJI = 'Teknoloji',
    EGITIM = 'Egitim',
    SAGLIK = 'Saglik',
    SEYAHAT = 'Seyahat',
    MODA = 'Moda',
    YEMEK = 'Yemek',
    TASARIM = 'Tasarim',
    SANAT = 'Sanat',
    HABER = 'Haber',
    SPOR = 'Spor',
    FINANS = 'Finans',
    YAZILIM = 'Yazilim',
    KARIYER = 'Kariyer',
    GELISIM = 'Gelisim',
    FOTOGRAFCILIK = 'Fotografcilik',
    DIJITAL = 'Dijital',
    OYUN = 'Oyun',
    EGLENCE = 'Eglence',
    DOGA = 'Doga',
    PSIKOLOJI = 'Psikoloji',
    FIKIRLER = 'Fikirler',
    GIRISIMCILIK = 'Girisimcilik',
    CEVRE = 'Cevre',
    EDEBIYAT = 'Edebiyat',
    MUZIK = 'Muzik',
}
